#!/bin/sh

# TODO how could it be started with the normal user? (not root-sudo)
#if ( pidof com.github.spheras.desktopfolder );then
#    killall com.github.spheras.desktopfolder
#fi
#su $USER -c "/usr/bin/com.github.spheras.desktopfolder &"
#
echo "Remember: You'll need to logout/reboot to launch the application."

exit 0
