#!/bin/sh

# TODO how could it be started with the normal user? (not root-sudo)
#if ( pidof com.github.spheras.desktopfolder );then
#    killall com.github.spheras.desktopfolder
#fi
#su $USER -c "/usr/bin/com.github.spheras.desktopfolder &"
#

#removing old instances
#killall com.github.spheras.desktopfolder

echo "Desktop Folder will automatically start the next time you log in, but you can begin using it by launching it like any other app."

exit 0
